### PR TITLE
add container files from hpc-stack

### LINKED ISSUE #3: Move container files from hpc-stack.
Move container files from hpc-stack.
Refer to hpc-stack issue https://github.com/NOAA-EMC/hpc-stack/issues/59

### PR DESCRIPTION
**Pull request by aerorahul**
This PR:
- adds container files from hpc-stack
- fixes #3

### CODE REVIEW

**Comment by MinsukJi-NOAA** [comment]
@aerorahul , I have some questions:
1. Do we need these many levels of intel-oneapi containers: ubuntu -> os-tools -> hpckit -> hpc-stack -> ufs-weather-model -> ufs-weather-model-lite?
2. Does the chain of hierarchy of containers work end to end? Has it been tested?
3. Does ufs-weather-model compile and run in Dockerfile.intel-oneapi-ufs-weather-model?
4. I see that you try to manage container sizes to some extent: deleting hpc-stack source dir & creating ufs-weather-model-lite. I think this is something that can be optimized further in the future. Of course this depends on which machines these containers will be used in, but nonetheless, small and lean container size is always better.

**Comment by aerorahul** [comment]
@MinsukJi-NOAA 
1. Yes.
Intel OneAPI, if you are not familiar with has ubuntu-os-tools as the base container.  The hpc-kit has to be built on top of this.  hpc-stack container is the next level in hierarchy. 
I suggest reading the Intel OneAPI docs to familiarize with how the Intel OneApi is organized.

UFS-weather-model container file is used to build the weather model develop inside of the hpc-kit container.
The ufs-weather-model-lite container assembles the components (libraries, executables) required to run.
This container is deployed and tested on AWS by PSL.

2. These end-to-end containers have been tested on AWS.

3. Yes.

**Comment by MinsukJi-NOAA** [comment]
In 1, I am not questioning whether we need all of them.  My question is do we need to separate them into different containers? I am aware of the pros of a modular approach, but building on many containers generate layers which can bloat the container size.

**Comment by aerorahul** [comment]
perhaps not.  Can we see the relative sizes of the containers through `$> docker images`.
I will create them and post that output.

Besides, these are recipes for generic Docker containers.  In a following PR, we should separate them into base and application.

**Comment by MinsukJi-NOAA** [comment]
OK

**Review by MinsukJi-NOAA — APPROVED** [review]

**Pull request merged**
